when:
  - event: [tag]

labels:
  platform: linux/amd64

steps:
  - name: build-android-image
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker rm -f yampa_android_builder || true
      - docker build -t yampa_android_builder -f docker/android.Dockerfile ./

  - name: build-android-apk
    image: docker
    environment:
      ANDROID_KEYSTORE_BASE64:
        from_secret: ANDROID_KEYSTORE_BASE64
      KEY_PROPERTIES:
        from_secret: KEY_PROPERTIES
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker create --name yampa_android_builder yampa_android_builder
      - echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > /tmp/upload-keystore.jks
      - echo "$KEY_PROPERTIES" > /tmp/key.properties
      - docker cp /tmp/upload-keystore.jks yampa_android_builder:/app/upload-keystore.jks
      - docker cp /tmp/key.properties yampa_android_builder:/app/android/key.properties
      - docker run -v android_sdks:/opt/android/sdks/ --name yampa_android_builder yampa_android_builder "flutter build apk --release"
      - mkdir -p dist
      - docker cp yampa_android_builder:/app/build/app/outputs/flutter-apk/app-release.apk dist/yampa-android-${CI_COMMIT_TAG}.apk
      - docker rm yampa_android_builder
      - ls -lh dist/

  - name: publish-release
    image: woodpeckerci/plugin-release
    settings:
      api_key:
        from_secret: GITEA_TOKEN
      files:
        - dist/yampa-android-${CI_COMMIT_TAG}.apk
      overwrite: true
