when:
  - event: [tag]

labels:
  platform: linux/amd64

steps:
  - name: build-linux-image
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker rm -f yampa_linux_builder || true
      - docker build -t yampa_linux_builder -f docker/linux.Dockerfile ./

  - name: build-linux-binaries
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker run -v appimage_binaries:/app/scripts/bin --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined --name yampa_linux_builder yampa_linux_builder "./scripts/build-linux-appimage.sh"
      - mkdir -p dist
      - docker cp yampa_linux_builder:/app/build/linux/x64/release/bundle dist/yampa-linux-release
      - tar -czvf dist/yampa-linux-x64-${CI_COMMIT_TAG}.tar.gz -C dist yampa-linux-release
      - docker cp yampa_linux_builder:/app/outputs/yampa-x64.AppImage dist/yampa-linux-x64-${CI_COMMIT_TAG}.AppImage
      - docker rm yampa_linux_builder
      - ls -lh dist/

  - name: publish-release
    image: woodpeckerci/plugin-release
    settings:
      api_key:
        from_secret: GITEA_TOKEN
      files:
        - dist/yampa-linux-x64-${CI_COMMIT_TAG}.tar.gz
        - dist/yampa-linux-x64-${CI_COMMIT_TAG}.AppImage
      overwrite: true
